l_simp_chinese:

 ###### 考古失败事件    ######

 # 古代哨兵系列
 ag_ancient_sentinels_part1:0 "§H[Root.GetLeaderName]§!在带领[Root.Owner.GetArchaeologyTeam]在§H[From.Planet.GetName]§!及其附近进行考古工作时，因为一些不明原因触发了某种古代防御机制，并遭到了一些造型怪异的古代哨兵的袭击。\n\n"
 ag_ancient_sentinels_part2_he:0 "幸运的是，大多数古代哨兵都由于长期缺乏维护而严重损坏了，我们的[Root.Owner.GetSecurityTeam]及时赶到，在激烈的交战后摧毁了剩余的那些可能会对我们的[Root.Owner.GetArchaeologyTeam]造成伤害的古代哨兵。\n\n事后，§H[Root.GetLeaderName]§!带领[Root.Owner.GetArchaeologyTeam]回收了这些古代哨兵的残骸并对它们进行了分析，从中获取了许多有价值的信息，并报告称这些信息将会对我们的考古工作起到不小的帮助。"
 ag_ancient_sentinels_part2_ne:0 "幸运的是，大多数古代哨兵都由于长期缺乏维护而严重损坏了，我们的[Root.Owner.GetSecurityTeam]及时赶到，在激烈的交战后摧毁了剩余的那些可能会对我们的[Root.Owner.GetArchaeologyTeam]造成伤害的古代哨兵。\n\n事后，§H[Root.GetLeaderName]§!带领[Root.Owner.GetArchaeologyTeam]回收了这些古代哨兵的残骸并对它们进行了分析，但是并没有任何有意义的发现，这次事件结束后，我们的考古工作很快就会回到正轨。"
 ag_ancient_sentinels_part2_be1:0 "这些古代哨兵早在我们的[Root.Owner.GetSecurityTeam]赶到前就已经对我们的[Root.Owner.GetArchaeologyTeam]展开了攻击，并对[Root.Owner.GetArchaeologyTeam]造成了惨重的伤亡。\n\n尽管这些古代哨兵最后在与我们的[Root.Owner.GetSecurityTeam]进行了激烈的交火后被全部摧毁，但这次事故让我们的[Root.Owner.GetArchaeologyTeam]蒙受了巨大的损失，许多工作关键部分的进度倒退了不少。"
 ag_ancient_sentinels_part2_be2:0 "\n\n更糟糕的是，这次事故也为§H[Root.GetLeaderName]§!带来了严重的负面影响。"
 ag_ancient_sentinels_part2_be3:0 "这些古代哨兵早在我们的[Root.Owner.GetSecurityTeam]赶到前就已经对我们的[Root.Owner.GetArchaeologyTeam]展开了攻击，不仅杀害了我们的[Root.Owner.GetArchaeologyTeam]包括§H[Root.GetLeaderName]§!在内的几乎全部成员，还为后来赶到的[Root.Owner.GetSecurityTeam]带来了惨重的伤亡。\n\n尽管这些古代哨兵最后在与我们的[Root.Owner.GetSecurityTeam]进行了激烈的交火后被全部摧毁，这次事故仍然让我们的[Root.Owner.GetArchaeologyTeam]几乎伤亡殆尽，如果想要继续进行考古工作，我们就不得不派出新的[Root.Owner.GetArchaeologyTeam]，并且之前的绝大部分工作都只能从新开始。"
 ag_ancient_sentinels_part2_be4:0 "我们的[Root.Owner.GetSecurityTeam]及时赶到，并在与古代哨兵激烈的交火中成功保护着我们的[Root.Owner.GetArchaeologyTeam]撤离到了安全的位置。\n\n不过我们的[Root.Owner.GetSecurityTeam]报告称，以现有的装备几乎不可能打败这些古代哨兵，并请求[Root.Owner.GetName]提供资金和一些能够更有效的对付这些古代哨兵的装备，否则他们只能继续等待直到这些古代哨兵自行离开，鉴于古代哨兵目前正在一片相当大的区域内活动并且丝毫没有想要离开的意思，如果我们选择等待，这可能会严重影响整个考古工作的进度。"

 ag_arc_failed.11.name:0 "古代哨兵"
 ag_arc_failed.11.desc:0 "$ag_ancient_sentinels_part1$$ag_ancient_sentinels_part2_he$"
 ag_arc_failed.11.a:0 "因祸得福。"

 ag_arc_failed.12.name:0 "$ag_arc_failed.11.name$"
 ag_arc_failed.12.desc:0 "$ag_ancient_sentinels_part1$$ag_ancient_sentinels_part2_ne$"
 ag_arc_failed.12.a:0 "这算是好事吧？"
 
 ag_arc_failed.13.name:0 "$ag_arc_failed.11.name$"
 ag_arc_failed.13.desc:0 "$ag_ancient_sentinels_part1$$ag_ancient_sentinels_part2_be1$"
 ag_arc_failed.13.a:0 "真是不幸……"
 
 ag_arc_failed.14.name:0 "$ag_arc_failed.11.name$"
 ag_arc_failed.14.desc:0 "$ag_ancient_sentinels_part1$$ag_ancient_sentinels_part2_be1$$ag_ancient_sentinels_part2_be2$"
 ag_arc_failed.14.a:0 "真是不幸……"
 
 ag_arc_failed.15.name:0 "$ag_arc_failed.11.name$"
 ag_arc_failed.15.desc:0 "$ag_ancient_sentinels_part1$$ag_ancient_sentinels_part2_be3$"
 ag_arc_failed.15.a:0 "真是不幸……"
 
 ag_arc_failed.16.name:0 "$ag_arc_failed.11.name$"
 ag_arc_failed.16.desc:0 "$ag_ancient_sentinels_part1$$ag_ancient_sentinels_part2_be4$"
 ag_arc_failed.16.a:0 "为我们的[Root.Owner.GetArchaeologyTeam]提供额外的资源。"
 ag_arc_failed.16.b:0 "我们没有资源给他们挥霍。"

 # 不稳定区域系列
 ag_unstable_area_part1:0 "§H[Root.GetLeaderName]§!在带领[Root.Owner.GetArchaeologyTeam]在§H[From.Planet.GetName]§!及其附近进行考古工作时，需要经过一片高度不稳定，随时可能发生塌方的区域。\n\n"
 ag_unstable_area_part2_he:0 "根据对该区域的安全评估，§H[Root.GetLeaderName]§!带领[Root.Owner.GetArchaeologyTeam]在出现塌方前迅速通过了该区域，随后发生的塌方没有给我们的[Root.Owner.GetArchaeologyTeam]带来任何损失。\n\n在确认区域彻底安全后，我们的[Root.Owner.GetArchaeologyTeam]在废墟中意外的发现了许多有用的线索，这显然会对我们的考古工作带来不小的帮助。"
 ag_unstable_area_part2_ne:0 "根据对该区域的安全评估，§H[Root.GetLeaderName]§!带领[Root.Owner.GetArchaeologyTeam]在出现塌方前迅速通过了该区域，随后发生的塌方没有给我们的[Root.Owner.GetArchaeologyTeam]带来任何损失。\n\n在确认区域彻底安全后，我们的[Root.Owner.GetArchaeologyTeam]对废墟进行了全面的分析，最终没有任何有意义的发现，考古工作很快将会回归正轨。"
 ag_unstable_area_part2_be1:0 "那个区域发生塌方时，部分我们的[Root.Owner.GetArchaeologyTeam]的成员正在受影响的区域工作，随后被确认在事故中死亡。\n\n这次事故为我们的[Root.Owner.GetArchaeologyTeam]带来了不小的损失，许多工作的进度倒退了一大截。"
 ag_unstable_area_part2_be2:0 "\n\n更糟糕的是，§H[Root.GetLeaderName]§!在这次事故后受到了不可逆的负面影响。"
 ag_unstable_area_part2_be3:0 "那个区域发生塌方时，§H[Root.GetLeaderName]§!正带领[Root.Owner.GetArchaeologyTeam]的大多数成员在受影响的区域工作，他们随后被确认在这次事故中死亡。\n\n这次事故为我们的[Root.Owner.GetArchaeologyTeam]带来的巨大的伤亡，如果想要继续进行考古工作，我们就不得不派出新的[Root.Owner.GetArchaeologyTeam]，并且之前的绝大部分工作都只能从新开始。"
 ag_unstable_area_part2_be4:0 "我们的[Root.Owner.GetArchaeologyTeam]对该区域的评估表明，这个区域在的不稳定程度已经远远超出了可以正常通过的阈值，我们的[Root.Owner.GetArchaeologyTeam]必须要花费大量的资源对那个区域进行加固，才可以保证他们能够安全的通过，但他们目前没有所需要的资源，除非[Root.Owner.GetName]提供帮助，否则他们只能花费额外的精力来寻找其它的路径。"

 ag_arc_failed.21.name:0 "不稳定的区域"
 ag_arc_failed.21.desc:0 "$ag_unstable_area_part1$$ag_unstable_area_part2_he$"
 ag_arc_failed.21.a:0 "$ag_arc_failed.11.a$"

 ag_arc_failed.22.name:0 "$ag_arc_failed.21.name$"
 ag_arc_failed.22.desc:0 "$ag_unstable_area_part1$$ag_unstable_area_part2_ne$"
 ag_arc_failed.22.a:0 "$ag_arc_failed.12.a$"
 
 ag_arc_failed.23.name:0 "$ag_arc_failed.21.name$"
 ag_arc_failed.23.desc:0 "$ag_unstable_area_part1$$ag_unstable_area_part2_be1$"
 ag_arc_failed.23.a:0 "$ag_arc_failed.13.a$"
 
 ag_arc_failed.24.name:0 "$ag_arc_failed.21.name$"
 ag_arc_failed.24.desc:0 "$ag_unstable_area_part1$$ag_unstable_area_part2_be1$$ag_unstable_area_part2_be2$"
 ag_arc_failed.24.a:0 "$ag_arc_failed.14.a$"
 
 ag_arc_failed.25.name:0 "$ag_arc_failed.21.name$"
 ag_arc_failed.25.desc:0 "$ag_unstable_area_part1$$ag_unstable_area_part2_be3$"
 ag_arc_failed.25.a:0 "$ag_arc_failed.15.a$"
 
 ag_arc_failed.26.name:0 "$ag_arc_failed.21.name$"
 ag_arc_failed.26.desc:0 "$ag_unstable_area_part1$$ag_unstable_area_part2_be4$"
 ag_arc_failed.26.a:0 "$ag_arc_failed.16.a$"
 ag_arc_failed.26.b:0 "$ag_arc_failed.16.b$"

 # 设备故障系列
 ag_equipment_malfunction_part1:0 "在§H[From.Planet.GetName]§!的[Root.Owner.GetArchaeologyTeam]报告称考古工作所需的关键设备出现了意料之外的故障。\n\n"
 ag_equipment_malfunction_part2_ne:0 "幸运的是，故障的设备得到了及时的修复，整个考古工作在短暂的停滞后得以继续进行。"
 ag_equipment_malfunction_part2_be1:0 "这些故障的设备长期得不到更换，导致考古工作计划中的几个关键步骤无法正常进行，因而整个工作已经停滞了一段时间了。"
 ag_equipment_malfunction_part2_be2:0 "这些故障的设备长期得不到更换，但我们的[Root.Owner.GetArchaeologyTeam]不得不使用这些设备，这导致我们的[Root.Owner.GetArchaeologyTeam]在工作中出现了许多不必要的伤亡，让整个考古工作的进展倒退了不少，而§H[Root.GetLeaderName]§!也在不断的事故中遭受了不可逆的负面影响。"
 ag_equipment_malfunction_part2_be3:0 "这些故障的设备长期得不到更换，但我们的[Root.Owner.GetArchaeologyTeam]不得不使用这些设备，这导致我们的[Root.Owner.GetArchaeologyTeam]在工作中遭遇了一次重大的事故，我们的[Root.Owner.GetArchaeologyTeam]损失了§H[Root.GetLeaderName]§!和[Root.Owner.GetArchaeologyTeam]的部分关键成员，整个考古工作的进展倒退了许多。"
 ag_equipment_malfunction_part2_be4:0 "这些故障的设备长期得不到更换，导致整个考古计划中的几个关键步骤无法进行，§H[Root.GetLeaderName]§!带领的[Root.Owner.GetArchaeologyTeam]再次要求[Root.Owner.GetName]提供额外的资源来更新设备，否则整个[Root.Owner.GetArchaeologyTeam]必须等待相当长一段时间，直到所需要的设备准备到位。"

 ag_arc_failed.32.name:0 "设备故障"
 ag_arc_failed.32.desc:0 "$ag_equipment_malfunction_part1$$ag_equipment_malfunction_part2_ne$"
 ag_arc_failed.32.a:0 "$ag_arc_failed.12.a$"
 
 ag_arc_failed.33.name:0 "$ag_arc_failed.32.name$"
 ag_arc_failed.33.desc:0 "$ag_equipment_malfunction_part1$$ag_equipment_malfunction_part2_be1$"
 ag_arc_failed.33.a:0 "$ag_arc_failed.13.a$"
 
 ag_arc_failed.34.name:0 "$ag_arc_failed.32.name$"
 ag_arc_failed.34.desc:0 "$ag_equipment_malfunction_part1$$ag_equipment_malfunction_part2_be2$"
 ag_arc_failed.34.a:0 "$ag_arc_failed.14.a$"
 
 ag_arc_failed.35.name:0 "$ag_arc_failed.32.name$"
 ag_arc_failed.35.desc:0 "$ag_equipment_malfunction_part1$$ag_equipment_malfunction_part2_be3$"
 ag_arc_failed.35.a:0 "$ag_arc_failed.15.a$"
 
 ag_arc_failed.36.name:0 "$ag_arc_failed.32.name$"
 ag_arc_failed.36.desc:0 "$ag_equipment_malfunction_part1$$ag_equipment_malfunction_part2_be4$"
 ag_arc_failed.36.a:0 "$ag_arc_failed.16.a$"
 ag_arc_failed.36.b:0 "$ag_arc_failed.16.b$"

 # 奇异的疾病系列
 ag_strange_disease_part1:0 "§H[Root.GetLeaderName]§!在带领[Root.Owner.GetArchaeologyTeam]在§H[From.Planet.GetName]§!及其附近进行考古工作时，遭遇了一种奇异的传染病，它不仅能够感染有机生命，还能对计算机系统造成严重的负面影响，可以在有机生命和计算机之间迅速传播。\n\n"
 ag_strange_disease_part2_ne:0 "§H[Root.GetLeaderName]§!和[Root.Owner.GetArchaeologyTeam]的几个关键成员及时发现了问题，并果断采取了控制措施，抑制住了传染病的传播，将损失控制在了最小范围内，考古工作在这次有惊无险的遭遇后得以继续进行。"
 ag_strange_disease_part2_be1:0 "当我们的[Root.Owner.GetArchaeologyTeam]意识到问题的严重性时，这种奇异的传染病已经给他们带来了不小的损失，不过在§H[Root.GetLeaderName]§!和其它所有[Root.Owner.GetArchaeologyTeam]成员的不懈努力下，传染病最终得到了控制，不过消除其带来的负面影响仍需一定时间。"
 ag_strange_disease_part2_be2:0 "当我们的[Root.Owner.GetArchaeologyTeam]意识到问题的严重性时，这种奇异的传染病已经在[Root.Owner.GetArchaeologyTeam]中蔓延开来了，而且由于§H[Root.GetLeaderName]§!和[Root.Owner.GetArchaeologyTeam]的其它成员没能及时采取有效的应对措施，当传染病最终得到控制时，整个[Root.Owner.GetArchaeologyTeam]已经损失惨重，§H[Root.GetLeaderName]§!也在这次事件中受到了不可逆的负面影响。"
 ag_strange_disease_part2_be3:0 "当我们的[Root.Owner.GetArchaeologyTeam]意识到问题的严重性时，这种奇异的传染病已经在[Root.Owner.GetArchaeologyTeam]中蔓延开来了，而且由于§H[Root.GetLeaderName]§!和[Root.Owner.GetArchaeologyTeam]的其它成员没能及时采取有效的应对措施，当传染病最终得到控制时，整个[Root.Owner.GetArchaeologyTeam]已经失去了包括§H[Root.GetLeaderName]§!在内，超过三分之二的成员，即使我们派出新的[Root.Owner.GetArchaeologyTeam]，大量的工作仍必须从头开始。"
 ag_strange_disease_part2_be4:0 "当我们的[Root.Owner.GetArchaeologyTeam]意识到问题的严重性时，这种奇异的传染病已经在[Root.Owner.GetArchaeologyTeam]中蔓延开来了，由于缺乏有效的应对措施，§H[Root.GetLeaderName]§!只能暂时采取严厉的隔离措施，尽最大可能控制传染病的传播。不过根据§H[Root.GetLeaderName]§!的报告，如果[Root.Owner.GetName]不提供额外的资源支持，[Root.Owner.GetArchaeologyTeam]将在这次事故中遭受惨重的损失，考古工作的进度也将倒退一大截。"

 ag_arc_failed.42.name:0 "奇异的传染病"
 ag_arc_failed.42.desc:0 "$ag_strange_disease_part1$$ag_strange_disease_part2_ne$"
 ag_arc_failed.42.a:0 "$ag_arc_failed.12.a$"
 
 ag_arc_failed.43.name:0 "$ag_arc_failed.42.name$"
 ag_arc_failed.43.desc:0 "$ag_strange_disease_part1$$ag_strange_disease_part2_be1$"
 ag_arc_failed.43.a:0 "$ag_arc_failed.13.a$"
 
 ag_arc_failed.44.name:0 "$ag_arc_failed.42.name$"
 ag_arc_failed.44.desc:0 "$ag_strange_disease_part1$$ag_strange_disease_part2_be2$"
 ag_arc_failed.44.a:0 "$ag_arc_failed.14.a$"
 
 ag_arc_failed.45.name:0 "$ag_arc_failed.42.name$"
 ag_arc_failed.45.desc:0 "$ag_strange_disease_part1$$ag_strange_disease_part2_be3$"
 ag_arc_failed.45.a:0 "$ag_arc_failed.15.a$"
 
 ag_arc_failed.46.name:0 "$ag_arc_failed.42.name$"
 ag_arc_failed.46.desc:0 "$ag_strange_disease_part1$$ag_strange_disease_part2_be4$"
 ag_arc_failed.46.a:0 "$ag_arc_failed.16.a$"
 ag_arc_failed.46.b:0 "$ag_arc_failed.16.b$"

 # 守护者系列
 ag_guardians_part1:0 "§H[Root.GetLeaderName]§!在带领[Root.Owner.GetArchaeologyTeam]在§H[From.Planet.GetName]§!及其附近进行考古工作时，发现前人留下的痕迹，此前的某个到访的文明将这里视为圣地，并在周围隐藏了一些对我们抱有敌意的守护者。\n\n"
 ag_guardians_part2_ne:0 "幸运的是，这个文明的科技水平远不及[Root.Owner.GetName]，我们的[Root.Owner.GetSecurityTeam]在接到[Root.Owner.GetArchaeologyTeam]的报告后，以极小的代价迅速消灭了这些守护者。\n\n我们的[Root.Owner.GetArchaeologyTeam]在事后对这些守护者的残骸进行了分析，但没有获得任何有价值的发现。"
 ag_guardians_part2_be1:0 "尽管这个文明的科技水平远不及[Root.Owner.GetName]，我们的[Root.Owner.GetArchaeologyTeam]仍在这些守护者的突然袭击下遭受了损失，在[Root.Owner.GetSecurityTeam]赶到前，有几个[Root.Owner.GetArchaeologyTeam]的成员被杀害了，这导致考古工作的进度出现了一定的损失。"
 ag_guardians_part2_be2:0 "\n\n更加令人难以置信的是，§H[Root.GetLeaderName]§!还在这次事故后遭受了一些不可逆的负面影响。"
 ag_guardians_part2_be3:0 "尽管这个文明的科技水平远不及[Root.Owner.GetName]，我们的[Root.Owner.GetArchaeologyTeam]仍在这些守护者的突然袭击下遭受了损失，在[Root.Owner.GetSecurityTeam]赶到前，有不少个[Root.Owner.GetArchaeologyTeam]的成员被杀害了，§H[Root.GetLeaderName]§!就是其中一个受害者，这导致我们的考古工作的进度出现了严重的损失。"
 ag_guardians_part2_be4:0 "虽然这个文明的科技水平远不及[Root.Owner.GetName]，但它们的守护者还是在被我们的[Root.Owner.GetSecurityTeam]摧毁前破坏了我们的[Root.Owner.GetArchaeologyTeam]需要经过的区域。\n\n根据我们的[Root.Owner.GetArchaeologyTeam]的报告，他们目前没有足够的资源来修复受损的区域，他们需要[Root.Owner.GetName]提供额外的资源，否则他们只能花费更多的时间来寻找其它的办法。"

 ag_arc_failed.52.name:0 "守护者"
 ag_arc_failed.52.desc:0 "$ag_guardians_part1$$ag_guardians_part2_ne$"
 ag_arc_failed.52.a:0 "$ag_arc_failed.12.a$"
 
 ag_arc_failed.53.name:0 "$ag_arc_failed.52.name$"
 ag_arc_failed.53.desc:0 "$ag_guardians_part1$$ag_guardians_part2_be1$"
 ag_arc_failed.53.a:0 "$ag_arc_failed.13.a$"
 
 ag_arc_failed.54.name:0 "$ag_arc_failed.52.name$"
 ag_arc_failed.54.desc:0 "$ag_guardians_part1$$ag_guardians_part2_be1$$ag_guardians_part2_be2$"
 ag_arc_failed.54.a:0 "$ag_arc_failed.14.a$"
 
 ag_arc_failed.55.name:0 "$ag_arc_failed.52.name$"
 ag_arc_failed.55.desc:0 "$ag_guardians_part1$$ag_guardians_part2_be3$"
 ag_arc_failed.55.a:0 "$ag_arc_failed.15.a$"
 
 ag_arc_failed.56.name:0 "$ag_arc_failed.52.name$"
 ag_arc_failed.56.desc:0 "$ag_guardians_part1$$ag_guardians_part2_be4$"
 ag_arc_failed.56.a:0 "$ag_arc_failed.16.a$"
 ag_arc_failed.56.b:0 "$ag_arc_failed.16.b$"

 # 气态巨行星风暴系列
 ag_gas_giant_storm_part1:0 "§H[Root.GetLeaderName]§!在带领[Root.Owner.GetArchaeologyTeam]在§H[From.Planet.GetName]§!及其附近进行考古工作时，遭遇了一场突如其来的风暴，我们的气候模型没能预报它的到来。\n\n"
 ag_gas_giant_storm_part2_ne:0 "幸运的是，风暴发生时，我们的[Root.Owner.GetArchaeologyTeam]成员都在$pc_gas_giant$的同步轨道上工作，因而未受到风暴的影响。"
 ag_gas_giant_storm_part2_be1:0 "\n\n但我们的[Root.Owner.GetArchaeologyTeam]部署在$pc_gas_giant$大气层内的许多设施在风暴中损坏了，修复工作需要持续相当长一段时间。"
 ag_gas_giant_storm_part2_be2:0 "风暴发生时，部分[Root.Owner.GetArchaeologyTeam]的成员正在我们部署在$pc_gas_giant$大气层内的设施里工作，没能在风暴中幸存下来。这次事故为我们的[Root.Owner.GetArchaeologyTeam]带来了不小的损失，也让我们的许多工作不得不放慢脚步，更糟糕的是，§H[Root.GetLeaderName]§!在这次事故中遭受了不可逆的负面影响。"
 ag_gas_giant_storm_part2_be3:0 "风暴发生时，§H[Root.GetLeaderName]§!正带领大多数[Root.Owner.GetArchaeologyTeam]在我们部署在$pc_gas_giant$大气层内的设施里工作，没能在风暴中幸存下来。这次事故使得我们的[Root.Owner.GetArchaeologyTeam]几乎伤亡殆尽，即使我们派出新的[Root.Owner.GetArchaeologyTeam]，许多工作也不得不从新开始。"
 ag_gas_giant_storm_part2_be4:0 "\n\n但我们的[Root.Owner.GetArchaeologyTeam]部署在$pc_gas_giant$大气层内的许多设施在风暴中损坏了，我们的[Root.Owner.GetArchaeologyTeam]要求[Root.Owner.GetName]提供额外的资源支持，否则不仅修复工作需要持续相当长一段时间，许多关键资料也将在这次事故中丢失。"

 ag_arc_failed.62.name:0 "$pc_gas_giant$风暴"
 ag_arc_failed.62.desc:0 "$ag_gas_giant_storm_part1$$ag_gas_giant_storm_part2_ne$"
 ag_arc_failed.62.a:0 "$ag_arc_failed.12.a$"
 
 ag_arc_failed.63.name:0 "$ag_arc_failed.62.name$"
 ag_arc_failed.63.desc:0 "$ag_gas_giant_storm_part1$$ag_gas_giant_storm_part2_ne$$ag_gas_giant_storm_part2_be1$"
 ag_arc_failed.63.a:0 "$ag_arc_failed.13.a$"
 
 ag_arc_failed.64.name:0 "$ag_arc_failed.62.name$"
 ag_arc_failed.64.desc:0 "$ag_gas_giant_storm_part1$$ag_gas_giant_storm_part2_be2$"
 ag_arc_failed.64.a:0 "$ag_arc_failed.14.a$"
 
 ag_arc_failed.65.name:0 "$ag_arc_failed.62.name$"
 ag_arc_failed.65.desc:0 "$ag_gas_giant_storm_part1$$ag_gas_giant_storm_part2_be3$"
 ag_arc_failed.65.a:0 "$ag_arc_failed.15.a$"
 
 ag_arc_failed.66.name:0 "$ag_arc_failed.62.name$"
 ag_arc_failed.66.desc:0 "$ag_gas_giant_storm_part1$$ag_gas_giant_storm_part2_ne$$ag_gas_giant_storm_part2_be4$"
 ag_arc_failed.66.a:0 "$ag_arc_failed.16.a$"
 ag_arc_failed.66.b:0 "$ag_arc_failed.16.b$"
 
 # 其他负面事件
 ag_arc_failed.71.name:0 "争执"
 ag_arc_failed.71.desc:0 "在§H[From.Planet.GetName]§!的[Root.Owner.GetArchaeologyTeam]传来了一份报告，称[Root.Owner.GetArchaeologyTeam]的领导§H[Root.GetLeaderName]§!与[Root.Owner.GetArchaeologyTeam]的几个主要成员在考古工作上出现了较大的分歧，并导致了考古工作长期进展缓慢，甚至一度停滞不前。"
 ag_arc_failed.71.a:0 "$ag_unfortunate$"
 
 ag_arc_failed.72.name:0 "天体运行"
 ag_arc_failed.72.desc:0 "由于§H[From.Planet.GetName]§!和它附近部分天体的影响，§H[Root.GetLeaderName]§!预计近段时间在§H[From.Planet.GetName]§!的考古工作的进展速度将会放缓。"
 ag_arc_failed.72.a:0 "$ag_OK$"
 
 ag_arc_failed.73.name:0 "补给问题"
 ag_arc_failed.73.desc:0 "根据§H[Root.GetLeaderName]§!的报告，在§H[From.Planet.GetName]§!及其附近进行考古工作的[Root.Owner.GetArchaeologyTeam]在不久前出现了一些补给问题，而且这些问题迟迟得不到解决，因而最近一段时间的考古工作进展速度必须放缓。"
 ag_arc_failed.73.a:0 "$ag_unfortunate$"
 
 ag_arc_failed.74.name:0 "腐败问题"
 ag_arc_failed.74.desc:0 "根据§H[Root.GetLeaderName]§!领导的[Root.Owner.GetArchaeologyTeam]成员的报告，§H[Root.GetLeaderName]§!和部分[Root.Owner.GetArchaeologyTeam]成员似乎有着严重的腐败问题，这导致我们的整个考古工作迟迟没有任何进展。"
 ag_arc_failed.74.a:0 "令人难以忍受。"
 
 # 其他正面事件
 ag_arc_failed.81.name:0 "前人的工作"
 ag_arc_failed.81.desc:0 "§H[Root.GetLeaderName]§!在带领[Root.Owner.GetArchaeologyTeam]在§H[From.Planet.GetName]§!及其附近进行考古工作时，发现了以前某个文明进行考古工作后留下的痕迹，尽管它们的工作最终因为我们不清楚的原因中止了，但它们留下的部分资料在经过简单的修复和翻译后仍然可以为我们所用。"
 ag_arc_failed.81.a:0 "$ag_excellent$"
 
 ag_arc_failed.82.name:0 "意外的发现"
 ag_arc_failed.82.desc:0 "§H[Root.GetLeaderName]§!在带领[Root.Owner.GetArchaeologyTeam]在§H[From.Planet.GetName]§!及其附近进行考古工作时，意外发现了一些对考古工作有价值的线索，这将会在一定程度上加快我们的[Root.Owner.GetArchaeologyTeam]进行考古工作的速度。"
 ag_arc_failed.82.a:0 "$ag_excellent$"
 
 ag_arc_failed.83.name:0 "隐藏的资源"
 ag_arc_failed.83.desc:0 "§H[Root.GetLeaderName]§!在带领[Root.Owner.GetArchaeologyTeam]在§H[From.Planet.GetName]§!及其附近进行考古工作时，找到了一些很久以前某个未知的文明遗留下来的资源，其中大多数资源都已经损坏了，但还有相当数量的资源可以使用。\n\n§H[Root.GetLeaderName]§!已经安排人手将可用的资源运送给[Root.Owner.GetName]政府，我们的考古工作将会按计划继续进行。"
 ag_arc_failed.83.a:0 "$ag_excellent$"